export enum WeaponTypes {
    pistol = "Pistol",
    rifle = "Rifle",
    shotgun = "Shotgun",
    sniperRifle = "Sniper rifle",
    submachineGun = "Submachine gun",
    lightmachineGun = "Light machine gun",
    mediumMachineGun = "Medium machine gun",
    heavyMachineGun = "Heavy machine gun",
    antiTankShoulderWeapon = "Shoulder-fired anti-tank weapon",
    flamethrower = "Flamethrower",
    mortar = "Mortar", 
    mine = "Mine",
    antiTankGun = "Anti-tank gun", 
}